[package]
name = "flipc"
authors = ["unworried"]
description = "The Flip Compiler"
edition = "2021"
version = "0.1.0"

[dependencies]
flipvm = { path = "../flipvm" }

[[bin]]
name = "debug"

[[bin]]
name = "repl"

[[bin]]
name = "compile"
