[package]
name = "flipvm"
version = "0.1.0"
authors = ["unworried"]
description = "The Flip Virtual Machine"
edition = "2021"
license = "MIT"

[dependencies]
macros = { path = "lib/macros" }

[[bin]]
name = "vm"

[[bin]]
name = "asm"

[[bin]]
name = "dis"
